// This file is used primarily to generate select box options while writing fewer lines of code in other .js files.
export default [
	'Anaheim Ducks',
	'Boston Bruins',
	'Buffalo Sabres',
	'Calgary Flames',
	'Carolina Hurricanes',
	'Chicago Blackhawks',
	'Colorado Avalanche',
	'Columbus Blue Jackets',
	'Dallas Stars',
	'Detroit Red Wings',
	'Edmonton Oilers',
	'Florida Panthers',
	'Los Angeles Kings',
	'Minnesota Wild',
	'Montreal Canadiens',
	'Nashville Predators',
	'New Jersey Devils',
	'New York Islanders',
	'New York Rangers',
	'Ottawa Senators',
	'Philadelphia Flyers',
	'Phoenix Coyotes',
	'Pittsburgh Penguins',
	'St. Louis Blues',
	'San Jose Sharks',
	'Tampa Bay Lightning',
	'Toronto Maple Leafs',
	'Vancouver Canucks',
	'Washington Capitals',
	'Winnipeg Jets'
];